### ISSUE TITLE
TrainingArguments(하이퍼파라미터)와 모델 코드 분리 - yaml, argsparse

### ISSUE THREAD

**Issue by lectura7942** [boostcampaitech5/level2_klue-nlp-07#16]
TrainingArguments를 yaml 파일에 따로 분리하는 방법입니다.
취향에 따라 사용하시면 될 것 같습니다.

# 1. yaml 파일에 분리

## 1-1. yaml 파일 (config.yaml)
`params`는 베이스라인에 있는 옵션과 동일합니다.

```yaml
# config.yaml
path:
  train_path: ../dataset/train/train_strat.csv
  dev_path: ../dataset/train/dev_strat.csv
  test_path: ../dataset/test/test_data.csv

model: klue/bert-base

params:
  output_dir: "./results"          # output directory
  save_strategy: 'steps' # "no" to stop
  evaluation_strategy: 'steps' # evaluation strategy to adopt during training
                                # `no`: No evaluation during training.
                                # `steps`: Evaluate every `eval_steps`.
                                # `epoch`: Evaluate every end of epoch.
                                # if load_best_model_at_end=True, should be same as save_strategy & save_steps=eval_steps 배수
  logging_strategy: 'steps'  # "no" to stop
  report_to: "wandb" # "none" to stop wandb logging
  save_total_limit: 2              # number of total save model.
  save_steps: 500                 # model saving step.
  num_train_epochs: 1              # total number of training epochs
  learning_rate: !!float 1e-5               # learning_rate
  per_device_train_batch_size: 8  # batch size per device during training
  per_device_eval_batch_size: 8   # batch size for evaluation
  warmup_steps: 500                # number of warmup steps for learning rate scheduler
  weight_decay: 0.01               # strength of weight decay
  logging_dir: "./logs"            # directory for storing logs
  logging_steps: 100              # log saving step.
  eval_steps : 500            # evaluation step.
  load_best_model_at_end : True # best checkpoint never deleted
```

- yaml은 자료형을 자동으로 인식해준다고 합니다. 문자열을 ""로 둘러싸도 되고, 없어도 됩니다.
- `learning_rate`에서 1e-5를 str로 인식해서, float 자료형으로 명시해줬습니다.

## 1-2. train.py

- `config.yaml`을 dict로 가져옵니다. (config.yaml 과 train.py 상대 경로 주의)
- HfArgumentParser를 사용해서 dict를 TrainingArguments로 변환합니다.
  - `parse_dict()`가 튜플을 반환해서 첫 번째 원소만 저장

```python
import yaml
from transformer import HfArgumentParser

def train():
  with open("./config.yaml") as file:
    config = yaml.safe_load(file) # yaml 파일을 dict로 불러온다.

   MODEL_NAME = config["model"]
  
  train_dataset = load_data(config["path"]["train_path"])
  dev_dataset = load_data(config["path"]["dev_path"])

  training_args = HfArgumentParser(TrainingArguments).parse_dict(config["params"])[0] # dict를 TrainingArguments 클래스로 변환
```

# 2. argsparse 사용

```
python3 train.py --model_name=klue/roberta-large --batch_size=32 --fp16=True --fix=True
```

## 2-1. train.py > \_\_main\_\_

```python
if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument('--model_name', default='klue/roberta-small', type=str)
  parser.add_argument('--batch_size', default=16, type=int)
  parser.add_argument('--max_epoch', default=5, type=int)
  parser.add_argument('--lr', default=float(5e-5), type=float) # learning_rate
  parser.add_argument('--warmup_steps', default=500, type=int)
  parser.add_argument('--weight_decay', default=0.01, type=float)
  parser.add_argument('--fp16', default=False, type=bool)
  parser.add_argument('--fix', default=False, type=bool) # fix seed
  parser.add_argument('--train_path', default="../dataset/train/train.csv")
  parser.add_argument('--dev_path', default="../dataset/train/dev.csv")
  parser.add_argument('--test_path', default="../dataset/test/test_data.csv")
  parser.add_argument('--project_name', default='re_models') # wandb
  parser.add_argument('--run_name', default='') # wandb
  parser.add_argument('--save', default='steps') # save_strategy
  parser.add_argument('--log', default='steps') # logging_strategy
  parser.add_argument('--eval', default='steps') # evaluation_strategy
  # evaluation strategy to adopt during training
  # `no`: No evaluation during training.
  # `steps`: Evaluate every `eval_steps`.
  # `epoch`: Evaluate every end of epoch.
  # if load_best_model_at_end=True, should be same as save_strategy & save_steps=eval_steps 배수
  
  args = parser.parse_args()
    
  # main()
  if args.fix:
    set_seed(42)
    
  print(args)
  train(args)
```

## 2-2. train.py > train()

```python
def train(args):
  # load model and tokenizer
  # MODEL_NAME = "bert-base-uncased"
  MODEL_NAME = args.model_name
  tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

  # load dataset
  train_dataset = load_data(args.train_path)
  dev_dataset = load_data(args.dev_path) # validation용 데이터는 따로 만드셔야 합니다.
  
  # (중략)

  # wandb run_name 설정
  now = datetime.now(timezone('Asia/Seoul')).strftime('%m-%d-%H:%M')
  run_name = f"{args.run_name}_{MODEL_NAME}_[b{args.batch_size},e{args.max_epoch},lr{args.lr}]_{now}"
  wandb.init(project=args.project_name, name=run_name)
  
  if args.save == "no":
    load_best_model_flag = False
  else:
    load_best_model_flag = True
    
  if args.log == "no":
    report_to = "none"
  else:
    report_to = "wandb"
  
  output_dir = f"results/{run_name}_{now}"
  
  # 사용한 option 외에도 다양한 option들이 있습니다.
  # https://huggingface.co/transformers/main_classes/trainer.html#trainingarguments 참고해주세요.
  training_args = TrainingArguments(
    output_dir=output_dir,          # output directory
    save_strategy = args.save, # "no" to stop
    evaluation_strategy=args.eval, # evaluation strategy to adopt during training
                                # `no`: No evaluation during training.
                                # `steps`: Evaluate every `eval_steps`.
                                # `epoch`: Evaluate every end of epoch.
                                # if load_best_model_at_end=True, should be same as save_strategy & save_steps=eval_steps 배수
    logging_strategy = args.log,  # "no" to stop
    report_to=report_to, # "none" to stop wandb logging
    save_total_limit=2,              # number of total save model.
    save_steps=500,                 # model saving step.
    num_train_epochs=args.max_epoch,              # total number of training epochs
    learning_rate=args.lr,               # learning_rate
    per_device_train_batch_size=args.batch_size,  # batch size per device during training
    per_device_eval_batch_size=args.batch_size,   # batch size for evaluation
    warmup_steps=args.warmup_steps,                # number of warmup steps for learning rate scheduler
    weight_decay=args.weight_decay,               # strength of weight decay
    logging_dir='./logs',            # directory for storing logs
    logging_steps=100,              # log saving step.
    eval_steps = 500,            # evaluation step.
    load_best_model_at_end = load_best_model_flag, # best checkpoint never deleted
    fp16=args.fp16
  )
  trainer = Trainer(
    model=model,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=RE_train_dataset,         # training dataset
    eval_dataset=RE_dev_dataset,             # evaluation dataset
    compute_metrics=compute_metrics         # define metrics function
  )

  # train model
  trainer.train()
  if args.save != "no":
    model.save_pretrained(f'{output_dir}/best_model')
```

# 참고: `training_args` 출력

```
TrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_find_unused_parameters=None,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_steps=500,
evaluation_strategy=IntervalStrategy.STEPS,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
gradient_accumulation_steps=1,
greater_is_better=False,
group_by_length=False,
ignore_data_skip=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=1e-05,
length_column_name=length,
load_best_model_at_end=True,
local_rank=-1,
log_level=-1,
log_level_replica=-1,
log_on_each_node=True,
logging_dir=./logs,
logging_first_step=False,
logging_steps=100,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
no_cuda=False,
num_train_epochs=1,
output_dir=./results,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=8,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=results,
push_to_hub_organization=None,
push_to_hub_token=None,
remove_unused_columns=True,
report_to=['wandb'],
resume_from_checkpoint=None,
run_name=./results,
save_on_each_node=False,
save_steps=500,
save_strategy=IntervalStrategy.STEPS,
save_total_limit=2,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_legacy_prediction_loop=False,
warmup_ratio=0.0,
warmup_steps=500,
weight_decay=0.01,
)
```
