### ISSUE TITLE
모델 비교 및 sweep (#19에 합침)

### ISSUE THREAD

**Issue by lectura7942** [boostcampaitech5/level2_klue-nlp-07#18]
# 1. 비교할 모델

huggingface `AutoModelForSequenceClassification`는 다음 사전 학습 모델을 지원합니다.
```
DistilBert, ALBERT, CamemBERT, XLM-RoBERTa, RoBERTa, Bert, XLNet, Flaubert
```
위 모델을 참고해서 한국어/다국어 사전학습 모델을 선정했습니다.
(**TODO** gpt는 패딩 방법 따로 해야 할 수도)

1. xlm-roberta-large
2. kykim/funnel-kor-base
3. kykim/bert-kor-base
4. bert-base-multilingual-uncased
5. sentence-transformers/xlm-r-large-en-ko-nli-ststb
6. beomi/KcELECTRA-base-v2022
7. snunlp/KR-ELECTRA-discriminator
8. skt/kogpt2-base-v2

# 2. sweep yaml 파일
```
program: train.py
method: bayes
metric:
  goal: maximize
  name: 'eval/micro f1 score'
parameters:
  max_epoch:
    value: 1
  batch_size:
    distribution: categorical
    values: [8, 16, 32]
  lr:
    distribution: categorical
    values: [1e-5, 2e-5, 3e-5, 5e-5]
  warmup_steps:
    distribution: categorical
    values: [500, 700, 1000]
  model_name:
    distribution: categorical
    values:
      - klue/roberta-base
      - xlm-roberta-large
      - kykim/funnel-kor-base
      - kykim/bert-kor-base
      - bert-base-multilingual-uncased
      - sentence-transformers/xlm-r-large-en-ko-nli-ststb
      - beomi/KcELECTRA-base-v2022
      - snunlp/KR-ELECTRA-discriminator
      - skt/kogpt2-base-v2
```
