### ISSUE TITLE
[EXP} 모델 비교를 위한 간단한 sweep

### ISSUE THREAD

**Issue by yunjinchoidev** [boostcampaitech5/level2_klue-nlp-07#19]
현재 sweep ~~진행중~~ -> 진행 완료

일단 모델 5개와 배치 사이즈 2개만 간략하게 넣어서 다시 돌리는 중입니다. 

wandb [링크](https://wandb.ai/yunjinchoidev/nlp07_klue/reports/Untitled-Report--Vmlldzo0MzI1MzUz?accessToken=3f3t6ec8nx6g7wyxvln0vqxyd493grnlvrq0psmz5vyaqhm1f0lsxypytymij9gr) 올려둡니다.

roberta - large, batch size 32 가 가장 좋게 나오는 것 같습니다.

학습률 조정은 안하였습니다.

```yaml

program: train.py
method: bayes
metric:
  goal: maximize
  name: micro f1 score
parameters:
  model_name:
    values:
      - monologg/koelectra-base-v3-discriminator
      - klue/roberta-large
      - monologg/kobert
      - taeminlee/kogpt2
      - hyunwoongko/kobart
    distribution: categorical
  batch_size:
    values: [16, 32]
    distribution: categorical

```
